### ISSUE TITLE
Config page throws QT errors in the latest Anki version (v23.10.1)

### ISSUE THREAD

**Issue by kaysik** [rjoudrey/chinese_stats#4]
Chinese Stats config page no longer works in the latest version of Anki.

First error was about the line `scroll_area.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)` so I commented it out.  Then I got a 2nd error:

Anki 23.10.1 (fac9e0ee) Python 3.9.15 Qt 6.6.0 PyQt 6.6.0
Platform: Windows-10-10.0.19045
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2024-01-05 20:33:57
Add-ons possibly involved: ⁨Chinese Stats⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.addons", line 985, in onConfig
  File "C:\Users\Pto\AppData\Roaming\Anki2\addons21\1959794557\config.py", line 163, in show_settings
    dialog.exec_()
AttributeError: 'QDialog' object has no attribute 'exec_'

So I cannot configure what fields to count hanzi stats for my new note type.  Graph still works great for existing notes though.

**Comment by Rendok** [comment]
you need to change `dialog.exec_()` to `dialog.exec()`.

For the one you commented out, `QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff` will do. And you need to import `from PyQt6 import QtCore`
